### ISSUE TITLE
Support configuration from a pyproject.toml

### ISSUE THREAD

**Issue by nstarman** [scientific-python/pytest-doctestplus#185]
`pytest` is working to make configuration via `pyproject.toml` preferred to `setup.cfg` (see Warning section in https://docs.pytest.org/en/7.1.x/reference/customize.html#setup-cfg). I've been playing around with moving `astropy`'s pytest settings and almost everything works except the `pytest-doctest` configuration. It would be great if `pytest-doctestplus` could also make this transition.

**Comment by pllim** [comment]
Are you interested in submitting a PR for this? 😸

**Comment by saimn** [comment]
Not sure what needs to be done, we only use pytest API to access the configuration ?

**Comment by nstarman** [comment]
From a perusal, ``doctest_subpackage_requires`` stands out as incompatible. There might be more issues.

```
doctest_subpackage_requires =
    astropy/wcs/* = scipy>2.0;numpy>1.14
    astropy/cosmology/* = scipy>1.0
```

**Comment by nstarman** [comment]
I'm not sure that pyproject.toml supports globs in dictionary keys. If it does, maybe that's the way to add support.

**Comment by stefanv** [comment]
It would be good to have `pyproject.toml` configuration support, so we are not forced to re-introduce a `setup.cfg` file.

**Comment by saimn** [comment]
`pyproject.toml` is already supported, and used by astropy. Some tests were added in #222 but maybe it should also be mentioned somewhere in the docs.

**Comment by pllim** [comment]
I added a couple of sentence in 9b747b879c2eeb6eabd7355154c1c1f5070e7e9f . If one of you are passionate about proper doc update, please submit a follow-up PR. Thanks!

**Comment by bsipocz** [comment]
> I added a couple of sentence in https://github.com/scientific-python/pytest-doctestplus/commit/9b747b879c2eeb6eabd7355154c1c1f5070e7e9f . If one of you are passionate about proper doc update, please submit a follow-up PR. Thanks!

please do PRs for small things, too, thanks!
