### ISSUE TITLE
PyPI org move?

### ISSUE THREAD

**Issue by pllim** [scientific-python/pytest-doctestplus#205]
Does Scientific Python has a PyPI org? See https://docs.pypi.org/organization-accounts/

If you do, we can also transfer this package over from https://pypi.org/org/astropy/

**Comment by jarrodmillman** [comment]
@stefanv requested one, but I don't think we've gotten a response yet.

**Comment by bsipocz** [comment]
Can we move it outside in the meantime, the whole org setup is very new anyway.

**Comment by pllim** [comment]
Okay, I removed it from the org. Took me a while to find that button. LoL.
