### ISSUE TITLE
ENH: Fix python 3.12 compatibility

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/pytest-doctestplus#208]
I've tried to add a python 3.12-dev job to the matrix in #207, but am running into various problems, which are not yet clear whether to due to #200 or something else. So I'm opening this issue as a blocker for the first new release under the new org.

**Comment by bsipocz** [comment]
Basically, I see a lot of failures about the assertions, and haven't yet pinned down what causes it:

```
FAILED tests/test_doctestplus.py::test_non_ignored_whitespace - AttributeError: type object 'reprec' has no attribute 'assertoutcome'
```

**Comment by pllim** [comment]
I don't see the assertoutcome error over at https://github.com/scientific-python/pytest-doctestplus/actions/runs/5481077119/jobs/9984965983?pr=207 . Might want to decouple between pytest-dev and Python 3.12 for debugging. There are breaking changes in pytest 8.0.dev too.

**Comment by bsipocz** [comment]
Yeah, that job is still messing with the numpy install, so stuck at an irrelevant point. 

I see those actual failures locally, with pytest 7.4, but then I'll upgrade.

**Comment by bsipocz** [comment]
Wonderful @pllim, tests pass with pytest-dev!
