### ISSUE TITLE
Document how to test Markdown documents

### ISSUE THREAD

**Issue by alicederyn** [scientific-python/pytest-doctestplus#220]
I can't work out how to test code inside Markdown files. Currently the plugin does not ignore the markup needed to wrap code snippets in Markdown, i.e. something like

````text
```python
>>> print('Hi')
Hi
```
````

will fail because the final triple-backtick is assumed to be part of the output. Adding an extra blank line is not an option because it changes the final output.

(Also, the only documentation on how to pick up markdown files is [in the `tests` directory](https://github.com/scientific-python/pytest-doctestplus/blob/45fc0e989614728415d3bed9f7f2f25d4834e73a/tests/test_doctestplus.py#L583), could this be added to the README too?)

**Comment by pllim** [comment]
I think you need this in your pytest options?

```cfg
doctest_plus = enabled
text_file_format = md
```

Example: https://github.com/astropy/astropy/blob/2f0dddaed850fe8624badc5bf8d279ac4125e345/setup.cfg#L126-L127

As for documentation improvement, I agree it isn't the best, PR is welcome! Thanks!

**Comment by pllim** [comment]
Actually, not sure if that works for you, because looks like it is only used in this package if "rst" is provided.

The glob stuff you found is actually inherited from pytest (https://docs.pytest.org/en/stable/how-to/doctest.html).

Not sure where the Markdown support even come from. We don't usually run that on Markdown over at Astropy. Must be inherited from pytest but they don't show any examples with Markdown over there.

**Comment by lpsinger** [comment]
Have you tried calling pytest with the flag `--doctest-glob '*.md'`?

**Comment by bsipocz** [comment]
> Not sure where the Markdown support even come from. We don't usually run that on Markdown over at Astropy. Must be inherited from pytest but they don't show any examples with Markdown over there.

I can just reiterate what I said before on this repo is that what astropy core does has little relevance here. The plugin has been used way widely than astropy. It certainly worked for testing code examples in a book manuscript, and I'm sure it worked for md files when it was added. It's an oversight that an explicit md test file hasn't been added, it could be along with a txt one to extend what we already have for rst and tex.

**Comment by lpsinger** [comment]
> It's an oversight that an explicit md test file hasn't been added, it could be along with a txt one to extend what we already have for rst and tex.

There _are_ tests for Markdown, and they are passing.

**Comment by bsipocz** [comment]
Yes, sorry, I updated the comment above. There aren't explicit markdown files in `tests/docs/`, but that shouldn't really matter.

**Comment by pllim** [comment]
But the test cases did not cover the triple backticks as stated in original post. 🤔

**Comment by lpsinger** [comment]
I have a Markdown document that I'm testing using pytest-doctestplus in this repository (the README file): https://github.com/skyportal/healpix-alchemy

It's working.

**Comment by alicederyn** [comment]
@lpsinger I see you have a blank line at the end of your pycon snippets too, good to know!

If this could all go into the Readme to help the next person, that would be great

**Comment by lpsinger** [comment]
So what did you need to do in order for this to work?

**Comment by alicederyn** [comment]
1. Add `--doctest-glob '*.md'`.
2. Add a blank line before the closing triple-backtick.

This does *not* affect the rendered output in GitHub like I remembered (not sure if that's a GitHub change or my memory being bad), but it *does* result in the copied text containing an extra blank line when you use the text-copy widget on GitHub.

Changing `python` to `pycon` changed how the result was syntax-highlighted, but had no effect on how the final blank newline was handled by GitHub.

**Comment by lpsinger** [comment]
See #221.
