### ISSUE TITLE
Tries to import `__main__.py`

### ISSUE THREAD

**Issue by flying-sheep** [scientific-python/pytest-doctestplus#229]
`__main__.py` doesn’t need a `if __name__ == '__main__'`, since it just exists to be a CLI

Therefore doctestplus shouldn‘t try to import it.

**Comment by pllim** [comment]
I don't think we can guess what is CLI and what isn't. You can skip a file if you want to.

https://github.com/scientific-python/pytest-doctestplus#skipping-tests

**Comment by flying-sheep** [comment]
You misunderstand; [`__main__.py` is a standard for defining CLIs in Python](https://docs.python.org/3/library/__main__.html#main-py-in-python-packages).

There’s no guesswork involved here. All code in files called `__main__.py` should be treated as if they were inside of a `if __name__ == '__main__':` block, i.e. not imported unless you want to run a CLI.

**Comment by pllim** [comment]
Ah, okay. For some reason, I never encountered this usage myself. Usually it is via entry points. Thanks for the clarification!
