### ISSUE TITLE
Doesn’t respect `--import-mode`

### ISSUE THREAD

**Issue by flying-sheep** [scientific-python/pytest-doctestplus#231]
You use `pytest`’s `import_path` function, but don’t pass the user’s preferred `--import-mode`.

**Comment by bsipocz** [comment]
@flying-sheep - Thank you for all the bug reports, it's really exciting to see that the plugin is being picked up by more and more packages. 
If you have any time to spare, we're very welcome PRs to fix these in a more timely manner.
