### ISSUE TITLE
Zenodo DOI not tied to GitHub release anymore

### ISSUE THREAD

**Issue by pllim** [scientific-python/pytest-doctestplus#234]
I am unable to find this repo under my Zenodo account for webhook activation. Not sure who can.

The DOI listed in README is currently pointed to old versions.

**Comment by pllim** [comment]
The webhook gives Error 409 on GitHub side. I cannot see this repo at all on Zenodo side, maybe need @jarrodmillman or @stefanv to activate Zenodo side webhook for `scientific-python/pytest-doctestplus` as org owners?

**Comment by jarrodmillman** [comment]
Is [this](https://github.com/zenodo/zenodo/issues/1814#issuecomment-620555444) or [this](https://github.com/zenodo/zenodo/issues/1596#issuecomment-524385982) relevant?

**Comment by pllim** [comment]
@jarrodmillman , I am not sure. I just know I cannot see any scientific-python repos in my Zenodo account. I can see my own stuff, `astropy`, and `spacetelescope orgs. I did resync on my Zenodo GitHub page a few hours ago, still nothing.

**Comment by jarrodmillman** [comment]
Would you mind trying the steps in [this](https://github.com/zenodo/zenodo/issues/1814#issuecomment-620555444) comment?

I tried enabling Zenodo as an org owner and couldn't find anything to do. If you have something specific you want me to try let me know, but I couldn't find anything that I could/should do.

**Comment by pllim** [comment]
@jarrodmillman , ah, sorry I missed that part. I clicked a button. Now it says:

`Zenodo -> Organizational Access -> Scientific Python -> Access Request Pending`

**Comment by jarrodmillman** [comment]
I just approved your request for Zenodo access to the scientific-python org. Let me know if you need anything else.

**Comment by pllim** [comment]
Phew, finally see it and I toggled it (back) on. Thanks!

I am going to delete the GitHub Release and re-create it from the same tag. Since the webhook was not enabled at all (instead of enabled but broken), I cannot just redeploy an old payload.

**Comment by pllim** [comment]
Yay, it worked! https://zenodo.org/records/10402248

Thanks again for the help! 🎅

**Comment by bsipocz** [comment]
> I am going to delete the GitHub Release and re-create it from the same tag

For the sake of completeness, shall we do the same for 1.0.0?


Also, do you know how I can make this, and my other libraries show up in my zenodo dashboard?

**Comment by pllim** [comment]
> For the sake of completeness, shall we do the same for 1.0.0?

Oh, hmm. Theoretically, you can delete https://github.com/scientific-python/pytest-doctestplus/releases/tag/v1.0.0 and then recreate it from the 1.0.0 tag, but I don't know if doing that after 1.1.0 would mess up the listing on Zenodo or not, because of the timestamps from which it received those webhook events.

> how I can make this, and my other libraries show up in my zenodo dashboard?

Did you click the resync on your Zenodo page for GitHub integration? I find that I had to click resync, and wait a bit for it to finish, and then reload that page on my browser.

**Comment by drammock** [comment]
> I don't know if doing that after 1.1.0 would mess up the listing on Zenodo or not

having recently needed to push some missing releases to Zenodo for MNE-Python, I can confirm that you need to do them in order, because Zenodo will link "current" to *whatever version was most recently picked up by its GH hook* (regardless of the version number / label attached to the release)

**Comment by bsipocz** [comment]
Oh, bummer then. 

Also, my zenodo still behaves weirdly, maybe if you have 5-10 minutes of time to zoom we could sort it out? (still nothing shows up on the dashboard but a couple of slidedecks, etc.)

**Comment by pllim** [comment]
@bsipocz , alas it is getting late here on East Coast. How about we arrange something for tomorrow Tue before 3 PM Eastern? Please DM. Thanks!
