### ISSUE TITLE
replace flake8 with Ruff

### ISSUE THREAD

**Issue by Borda** [scientific-python/pytest-doctestplus#235]
Hello, have been using this package for a while and like it. I would like to make some small contributions back so I would suggest replacing the `flake8` linter with [Ruff](https://github.com/astral-sh/ruff) which is much faster and enables in addition more customization and applying other rules for code enhancement...

**Comment by bsipocz** [comment]
Thanks, but I'm 👎 on this. 

The plugin is a small enough package that linter speed shouldn't matter at all, and I would rather review PRs that address one of the many feature requests than ones focusing on code refactorings to fix some ruff rules.

**Comment by bsipocz** [comment]
@Borda - I hope this didn't come across as harsh. We more than welcome contributions of features or fixes, even if they are not in the current list.
