### ISSUE TITLE
BUG: generate-diff removes part of command not just the output

### ISSUE THREAD

**Issue by bsipocz** [scientific-python/pytest-doctestplus#252]
I run into this diff with a pyvo narrative docs file, where the print has been erroneously removed.

cc @seberg in case you have an idea what goes wrong (besides that the doc would probably benefit of a refactor that removes the printing in for loop altogether)

```
--- a/docs/dal/index.rst
+++ b/docs/dal/index.rst
@@ -719,17 +719,17 @@ Iterating over a resultset gives the rows in the result:
 .. doctest-remote-data::
 
     >>> for row in resultset:
-    ...     print(row['s_fov'])
-    0.05027778
-    0.05027778
+    0.06527778
+    0.06527778
+    0.06527778
+    0.06527778
+    0.06527778
+    0.06527778
     0.05027778
     0.05027778
     0.05027778
     0.05027778
     0.06527778
-    0.06527778
-    0.06527778
-    0.06527778
 
 The total number of rows in the answer is available as its ``len()``:
 ```

**Comment by seberg** [comment]
My guess is that I replace lines in the file, but completely forgot to account for the possibility of multi-line input.  (i.e. doctest plus finds it as the first line, but it spans more than one line, so the result ends later).

**Comment by bsipocz** [comment]
Oh, that may also explain why it left one of the `0.06527778` lines at the bottom.
